---
- name: bootstrapping server Prod
  hosts: prod
  become: yes

  tasks:
    - name: Ensure nginx package is present
      apt:
        name: nginx
        state: present

    - name: Ensure php extension matches new pattern
      lineinfile:
        path: /var/www/html/index.nginx-debian.html
        search_string: '<h1>Welcome to nginx!</h1>'
        line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
#        present: absent